### ISSUE TITLE
Espace de stockage des pictogrammes

### ISSUE THREAD

**Issue by Vincent-Espagne-1** [1twitif/social-viz#6]

**Comment by Vincent-Espagne-1** [comment]
Où peut-on stocker les pictogrammes ?

**Comment by GammaNu** [comment]
les picto destinés aux barres d'outils générique ou à l'interface globale de l'applications sont à mettre ici :
https://github.com/1twitif/social-viz/tree/master/staticApp/appImg
les picto spécifiques aux données d'un projet précis sont pour l'instant à mettre là :
https://github.com/1twitif/social-viz/tree/master/allData/picto
mais ce second dossier est suceptible de changer. (le premier aussi mais juste d'être renomé en picto)
En effet, je n'ai pas encore trouvé/choisi comment gérer l'évolution de l'application commune a chaque projet en parallèle de l'évolution spécifique de chaque projet (formulaire, picto, données spécifique, voir plus).

**Comment by GammaNu** [comment]
En attendant, me les envoyer dans un zip par email, avec l'objet du mail contenant  "picto" et le nom du projet correspondant me permettra de les retrouver facilement quand je les intégrerai.
